In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 1.8 MB/s  0:00:06m0:00:0100:01
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 2.8 MB/s  0:00:06m0:00:0100:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [4]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

df = pd.read_excel('Planilha todas as cidade ESAVI.xlsx')


print("Colunas identificadas:", df.columns.tolist())
df.head()

Colunas identificadas: ['Município de vacinação', 'Idade Evento', 'Data da Notificação', 'Raça/Cor', 'Sexo', 'Imunobiológico (vacina)', 'Dose', 'Gestante', 'Mês de gestação', 'Mulher amamentando no momento da vacinação?', 'Tipo de Evento', 'Reação / evento adverso', 'Classificação de gravidade', 'Gravidade', 'Desfecho (evolução do caso)', 'Doenças (CID10) - Preexistente', 'Medicamento em uso anterior ou durante a vacinação', 'Nome do Medicamento', 'Houve atendimento médico?', 'Tipo de Atendimento']

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
1,Abadiânia,18.0,2022-02-16 00:00:00,Parda,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose / 3: 3ª dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
2,Abadiânia,18.0,2022-02-16 00:00:00,Parda,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: - 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
3,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
4,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0

In [6]:

df.to_csv('dados_esavi_limpo.csv', index=False, encoding='utf-8')

print("Novo CSV gerado com sucesso!")

Novo CSV gerado com sucesso!

In [11]:
import pandas as pd
df = pd.read_csv('vacinaESAVI.csv')
df.head(2)

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
1,Abadiânia,18.0,2022-02-16 00:00:00,Parda,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose / 3: 3ª dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0

In [8]:
df.dtypes

Município de vacinação                                    str
Idade Evento                                          float64
Data da Notificação                                       str
Raça/Cor                                                  str
Sexo                                                      str
Imunobiológico (vacina)                                   str
Dose                                                      str
Gestante                                                  str
Mês de gestação                                       float64
Mulher amamentando no momento da vacinação?               str
Tipo de Evento                                            str
Reação / evento adverso                                   str
Classificação de gravidade                                str
Gravidade                                                 str
Desfecho (evolução do caso)                               str
Doenças (CID10) - Preexistente                            str
Medicamento em uso anterior ou durante a vacinação        str
Nome do Medicamento                                       str
Houve atendimento médico?                                 str
Tipo de Atendimento                                       str
dtype: object

In [10]:
nome_da_coluna = 'Data da Notificação'
df[nome_da_coluna] = pd.to_datetime(df[nome_da_coluna], format='%d/%m/%Y', errors='coerce')
print(df[nome_da_coluna].dtype)

datetime64[s]

In [12]:
df.isnull().any()

Município de vacinação                                True
Idade Evento                                          True
Data da Notificação                                   True
Raça/Cor                                              True
Sexo                                                  True
Imunobiológico (vacina)                               True
Dose                                                  True
Gestante                                              True
Mês de gestação                                       True
Mulher amamentando no momento da vacinação?           True
Tipo de Evento                                        True
Reação / evento adverso                               True
Classificação de gravidade                            True
Gravidade                                             True
Desfecho (evolução do caso)                           True
Doenças (CID10) - Preexistente                        True
Medicamento em uso anterior ou durante a vacinação    True
Nome do Medicamento                                   True
Houve atendimento médico?                             True
Tipo de Atendimento                                   True
dtype: bool

In [13]:
# Mostra a contagem de valores vazios por coluna
df.isnull().sum()

Município de vacinação                                  8
Idade Evento                                            8
Data da Notificação                                     8
Raça/Cor                                                8
Sexo                                                    8
Imunobiológico (vacina)                                 8
Dose                                                    9
Gestante                                                8
Mês de gestação                                         8
Mulher amamentando no momento da vacinação?             8
Tipo de Evento                                          8
Reação / evento adverso                                14
Classificação de gravidade                              9
Gravidade                                               8
Desfecho (evolução do caso)                             9
Doenças (CID10) - Preexistente                         45
Medicamento em uso anterior ou durante a vacinação    169
Nome do Medicamento                                     8
Houve atendimento médico?                               8
Tipo de Atendimento                                     8
dtype: int64

In [16]:
# Preenche os campos de texto vazios de colunas específicas
df['Município de vacinação'] = df['Município de vacinação'].fillna('Indefinido')
df['Idade Evento'] = df['Idade Evento'].fillna('Não informado')
df['Data da Notificação'] = df['Data da Notificação'].fillna('Não informado')
df['Raça/Cor'] = df['Raça/Cor'].fillna('Não informado')
df['Sexo'] = df['Sexo'].fillna('Não informado')
df['Imunobiológico (vacina)'] = df['Imunobiológico (vacina)'].fillna('Não informado')
df['Dose'] = df['Dose'].fillna('Não informado')
df['Gestante'] = df['Gestante'].fillna('Não informado')
df['Mês de gestação'] = df['Mês de gestação'].fillna('Não informado')
df['Mulher amamentando no momento da vacinação?'] = df['Mulher amamentando no momento da vacinação?'].fillna('Não informado')
df['Tipo de Evento'] = df['Tipo de Evento'].fillna('Não informado')
df['Reação / evento adverso'] = df['Reação / evento adverso'].fillna('Não informado')
df['Classificação de gravidade'] = df['Classificação de gravidade'].fillna('Não informado')
df['Gravidade'] = df['Gravidade'].fillna('Não informado')
df['Desfecho (evolução do caso)'] = df['Desfecho (evolução do caso)'].fillna('Não informado')
df['Doenças (CID10) - Preexistente'] = df['Doenças (CID10) - Preexistente'].fillna('Não informado')
df['Medicamento em uso anterior ou durante a vacinação'] = df['Medicamento em uso anterior ou durante a vacinação'].fillna('Não informado')
df['Nome do Medicamento'] = df['Nome do Medicamento'].fillna('Não informado')
df['Houve atendimento médico?'] = df['Houve atendimento médico?'].fillna('Não informado')
df['Tipo de Atendimento'] = df['Tipo de Atendimento'].fillna('Não informado')


# Mostra o resultado
df.head()

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
1,Abadiânia,18.0,2022-02-16 00:00:00,Parda,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose / 3: 3ª dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
2,Abadiânia,18.0,2022-02-16 00:00:00,Parda,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: - 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
3,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
4,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0

In [ ]:
#Removendo linhas em branco 
df=df.drop([10,20,182,189,219,242,414,444])

KeyError: '[10, 20, 182, 189, 219, 242, 414, 444] not found in axis'

In [20]:
# Apaga linhas duplicadas
df = df.drop_duplicates()

In [ ]:
# Excluindo coluna redundante
df = df.drop(columns=['Gravidade'])

In [23]:
# Selecionando apenas as colunas que são do tipo texto
colunas_texto = df.select_dtypes(include=['object', 'string']).columns

for col in colunas_texto:
    # Transformando em maiúsculo todas as String e removendo espaços em branco invisíveis nas pontas
    df[col] = df[col].astype(str).str.upper().str.strip()

In [24]:
df.head()

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,ABADIÂNIA,18.0,2022-02-16 00:00:00,BRANCA,MASCULINO,1: ASTRAZENECA/FIOCRUZ,1: 1ª DOSE,NÃO,0.0,NÃO,1: ERRO DE IMUNIZAÇÃO,1: DOSE INADEQUADA,1: NÃO GRAVE,0,1: CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
1,ABADIÂNIA,18.0,2022-02-16 00:00:00,PARDA,MASCULINO,1: ASTRAZENECA/FIOCRUZ,1: 1ª DOSE / 2: 2ª DOSE / 3: 3ª DOSE,NÃO,0.0,NÃO,1: ERRO DE IMUNIZAÇÃO,1: DOSE INADEQUADA,1: NÃO GRAVE,0,1: CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
2,ABADIÂNIA,18.0,2022-02-16 00:00:00,PARDA,FEMININO,1: ASTRAZENECA/FIOCRUZ,1: 1ª DOSE / 2: - 2ª DOSE,NÃO,0.0,NÃO,1: ERRO DE IMUNIZAÇÃO,1: DOSE INADEQUADA,1: NÃO GRAVE,0,1: CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
3,ABADIÂNIA,18.0,2022-02-16 00:00:00,BRANCA,FEMININO,1: ASTRAZENECA/FIOCRUZ,1: 1ª DOSE / 2: 2ª DOSE,NÃO,0.0,NÃO,1: ERRO DE IMUNIZAÇÃO,1: DOSE INADEQUADA,1: NÃO GRAVE,0,1: CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
4,ABADIÂNIA,18.0,2022-02-16 00:00:00,BRANCA,FEMININO,1: ASTRAZENECA/FIOCRUZ,1: 1ª DOSE,NÃO,0.0,NÃO,1: ERRO DE IMUNIZAÇÃO,1: DOSE INADEQUADA,1: NÃO GRAVE,0,1: CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0

In [25]:
# Removendo o padrão "1: " do início dos textos
df['Imunobiológico (vacina)'] = df['Imunobiológico (vacina)'].str.replace(r'^\d+:\s*', '', regex=True)
df['Dose'] = df['Dose'].str.replace(r'^\d+:\s*', '', regex=True)
df['Tipo de Evento'] = df['Tipo de Evento'].str.replace(r'^\d+:\s*', '', regex=True)
df['Reação / evento adverso'] = df['Reação / evento adverso'].str.replace(r'^\d+:\s*', '', regex=True)
df['Classificação de gravidade'] = df['Classificação de gravidade'].str.replace(r'^\d+:\s*', '', regex=True)
df['Desfecho (evolução do caso)'] = df['Desfecho (evolução do caso)'].str.replace(r'^\d+:\s*', '', regex=True)
df['Doenças (CID10) - Preexistente'] = df['Doenças (CID10) - Preexistente'].str.replace(r'^\d+:\s*', '', regex=True)
df['Nome do Medicamento'] = df['Nome do Medicamento'].str.replace(r'^\d+:\s*', '', regex=True)
df['Tipo de Atendimento'] = df['Tipo de Atendimento'].str.replace(r'^\d+:\s*', '', regex=True)

df.head()

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,ABADIÂNIA,18.0,2022-02-16 00:00:00,BRANCA,MASCULINO,ASTRAZENECA/FIOCRUZ,1ª DOSE,NÃO,0.0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,0,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
1,ABADIÂNIA,18.0,2022-02-16 00:00:00,PARDA,MASCULINO,ASTRAZENECA/FIOCRUZ,1ª DOSE / 2: 2ª DOSE / 3: 3ª DOSE,NÃO,0.0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,0,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
2,ABADIÂNIA,18.0,2022-02-16 00:00:00,PARDA,FEMININO,ASTRAZENECA/FIOCRUZ,1ª DOSE / 2: - 2ª DOSE,NÃO,0.0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,0,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
3,ABADIÂNIA,18.0,2022-02-16 00:00:00,BRANCA,FEMININO,ASTRAZENECA/FIOCRUZ,1ª DOSE / 2: 2ª DOSE,NÃO,0.0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,0,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
4,ABADIÂNIA,18.0,2022-02-16 00:00:00,BRANCA,FEMININO,ASTRAZENECA/FIOCRUZ,1ª DOSE,NÃO,0.0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,0,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0

In [28]:
# Excluindo coluna redundante
df = df.drop(columns=['Gravidade'])

KeyError: "['Gravidade'] not found in axis"

In [29]:
df.head()

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,ABADIÂNIA,18.0,2022-02-16 00:00:00,BRANCA,MASCULINO,ASTRAZENECA/FIOCRUZ,1ª DOSE,NÃO,0.0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
1,ABADIÂNIA,18.0,2022-02-16 00:00:00,PARDA,MASCULINO,ASTRAZENECA/FIOCRUZ,1ª DOSE / 2: 2ª DOSE / 3: 3ª DOSE,NÃO,0.0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
2,ABADIÂNIA,18.0,2022-02-16 00:00:00,PARDA,FEMININO,ASTRAZENECA/FIOCRUZ,1ª DOSE / 2: - 2ª DOSE,NÃO,0.0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
3,ABADIÂNIA,18.0,2022-02-16 00:00:00,BRANCA,FEMININO,ASTRAZENECA/FIOCRUZ,1ª DOSE / 2: 2ª DOSE,NÃO,0.0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
4,ABADIÂNIA,18.0,2022-02-16 00:00:00,BRANCA,FEMININO,ASTRAZENECA/FIOCRUZ,1ª DOSE,NÃO,0.0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0

In [30]:
print("Idade mínima:", df['Idade Evento'].min())
print("Idade máxima:", df['Idade Evento'].max())

Idade mínima: 0.0
Idade máxima: 90.0

In [33]:
# Exibindo em forma de inteiros 

df['Idade Evento'] = pd.to_numeric(df['Idade Evento'], errors='coerce').astype('Int64')


df['Mês de gestação'] = pd.to_numeric(df['Mês de gestação'], errors='coerce').astype('Int64')

df.head()

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,ABADIÂNIA,18,2022-02-16 00:00:00,BRANCA,MASCULINO,ASTRAZENECA/FIOCRUZ,1ª DOSE,NÃO,0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
1,ABADIÂNIA,18,2022-02-16 00:00:00,PARDA,MASCULINO,ASTRAZENECA/FIOCRUZ,1ª DOSE / 2: 2ª DOSE / 3: 3ª DOSE,NÃO,0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
2,ABADIÂNIA,18,2022-02-16 00:00:00,PARDA,FEMININO,ASTRAZENECA/FIOCRUZ,1ª DOSE / 2: - 2ª DOSE,NÃO,0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
3,ABADIÂNIA,18,2022-02-16 00:00:00,BRANCA,FEMININO,ASTRAZENECA/FIOCRUZ,1ª DOSE / 2: 2ª DOSE,NÃO,0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0
4,ABADIÂNIA,18,2022-02-16 00:00:00,BRANCA,FEMININO,ASTRAZENECA/FIOCRUZ,1ª DOSE,NÃO,0,NÃO,ERRO DE IMUNIZAÇÃO,DOSE INADEQUADA,NÃO GRAVE,CURA SEM SEQUELAS,0,NÃO,NÃO,NÃO,0

In [34]:
df.to_csv('vacinaESAVI.csv', index=False, encoding='utf-8')

In [35]:
#Dividindo a em colunas as doses
colunas_vacina = df['Dose'].str.split('/', expand=True)

print(colunas_vacina.head())

          0               1            2    3    4    5
0   1ª DOSE             NaN          NaN  NaN  NaN  NaN
1  1ª DOSE      2: 2ª DOSE    3: 3ª DOSE  NaN  NaN  NaN
2  1ª DOSE    2: -  2ª DOSE          NaN  NaN  NaN  NaN
3  1ª DOSE       2: 2ª DOSE          NaN  NaN  NaN  NaN
4   1ª DOSE             NaN          NaN  NaN  NaN  NaN

In [37]:
colunas_vacina.columns = ['Dose 1', 'Dose 2', 'Dose 3', 'Dose 4', 'Dose 5', 'Dose 6']

# Removendo a coluna bagunçada original do DataFrame
df_limpo = df.drop('Dose', axis=1)

# Concatenando (colando lado a lado) a tabela limpa 
df_final = pd.concat([df_limpo, colunas_vacina], axis=1)

print(df_final.head())

  Município de vacinação  Idade Evento  Data da Notificação Raça/Cor  \
0              ABADIÂNIA            18  2022-02-16 00:00:00   BRANCA
1              ABADIÂNIA            18  2022-02-16 00:00:00    PARDA
2              ABADIÂNIA            18  2022-02-16 00:00:00    PARDA
3              ABADIÂNIA            18  2022-02-16 00:00:00   BRANCA
4              ABADIÂNIA            18  2022-02-16 00:00:00   BRANCA

        Sexo Imunobiológico (vacina) Gestante  Mês de gestação  \
0  MASCULINO     ASTRAZENECA/FIOCRUZ      NÃO                0
1  MASCULINO     ASTRAZENECA/FIOCRUZ      NÃO                0
2   FEMININO     ASTRAZENECA/FIOCRUZ      NÃO                0
3   FEMININO     ASTRAZENECA/FIOCRUZ      NÃO                0
4   FEMININO     ASTRAZENECA/FIOCRUZ      NÃO                0

  Mulher amamentando no momento da vacinação?      Tipo de Evento  ...  \
0                                         NÃO  ERRO DE IMUNIZAÇÃO  ...
1                                         NÃO  ERRO DE IMUNIZAÇÃO  ...
2                                         NÃO  ERRO DE IMUNIZAÇÃO  ...
3                                         NÃO  ERRO DE IMUNIZAÇÃO  ...
4                                         NÃO  ERRO DE IMUNIZAÇÃO  ...

  Medicamento em uso anterior ou durante a vacinação Nome do Medicamento  \
0                                                NÃO                 NÃO
1                                                NÃO                 NÃO
2                                                NÃO                 NÃO
3                                                NÃO                 NÃO
4                                                NÃO                 NÃO

  Houve atendimento médico? Tipo de Atendimento    Dose 1          Dose 2  \
0                       NÃO                   0   1ª DOSE             NaN
1                       NÃO                   0  1ª DOSE      2: 2ª DOSE
2                       NÃO                   0  1ª DOSE    2: -  2ª DOSE
3                       NÃO                   0  1ª DOSE       2: 2ª DOSE
4                       NÃO                   0   1ª DOSE             NaN

        Dose 3 Dose 4 Dose 5 Dose 6
0          NaN    NaN    NaN    NaN
1   3: 3ª DOSE    NaN    NaN    NaN
2          NaN    NaN    NaN    NaN
3          NaN    NaN    NaN    NaN
4          NaN    NaN    NaN    NaN

[5 rows x 24 columns]